import { chainIds } from '@airswap/constants'

export const tokenListURLs = {
  [chainIds.MAINNET]: [
    'https://raw.githubusercontent.com/compound-finance/token-list/master/compound.tokenlist.json',
    'https://umaproject.org/uma.tokenlist.json',
    'https://raw.githubusercontent.com/SetProtocol/uniswap-tokenlist/main/set.tokenlist.json',
    'https://app.tryroll.com/tokens.json',
    'https://tokens.coingecko.com/uniswap/all.json',
    'https://zapper.fi/api/token-list',
    'https://tokenlist.aave.eth.link',
    'https://tokens.coingecko.com/ethereum/all.json',
  ],
  [chainIds.BSC]: [
    'https://raw.githubusercontent.com/ApeSwapFinance/apeswap-token-lists/main/lists/apeswap.json',
    'https://tokens.pancakeswap.finance/pancakeswap-top-100.json',
    'https://tokens.pancakeswap.finance/pancakeswap-extended.json',
  ],
  [chainIds.POLYGON]: [
    'https://unpkg.com/quickswap-default-token-list@1.2.9/build/quickswap-default.tokenlist.json',
    'https://storageapi.fleek.co/tomafrench-team-bucket/polygon.vetted.tokenlist.json',
  ],
  [chainIds.OPTIMISM]: ['https://static.optimism.io/optimism.tokenlist.json'],
  [chainIds.ARBITRUM]: [
    'https://bridge.arbitrum.io/token-list-42161.json',
    'https://tracer.finance/tokens',
    'https://storageapi.fleek.co/tomafrench-team-bucket/arbitrum.vetted.tokenlist.json',
  ],
  [chainIds.AVALANCHE]: [
    'https://matcha.xyz/tokenlists/43114.json',
    'https://raw.githubusercontent.com/pangolindex/tokenlists/main/defi.tokenlist.json',
    'https://raw.githubusercontent.com/pangolindex/tokenlists/main/stablecoin.tokenlist.json',
    'https://raw.githubusercontent.com/pangolindex/tokenlists/main/ab.tokenlist.json',
    'https://raw.githubusercontent.com/traderjoe-xyz/joe-tokenlists/main/joe.tokenlist.json',
  ],
}

export const openSeaUrls = {
  1: 'https://api.opensea.io/api/v1',
  4: 'https://testnets-api.opensea.io/api/v1',
}

export const defaults = [
  {
    name: 'Wrapped Ether',
    address: '0xc778417e063141139fce010982780140aa0cd5ab',
    decimals: 18,
    symbol: 'WETH',
    chainId: 4,
  },
  {
    name: 'Wrapped Ether',
    address: '0xb4fbf271143f4fbf7b91a5ded31805e42b2208d6',
    decimals: 18,
    symbol: 'WETH',
    chainId: 5,
  },
  {
    name: 'Wrapped Ether',
    address: '0xd0a1e359811322d97991e03f863a0c30c2cf029c',
    decimals: 18,
    symbol: 'WETH',
    chainId: 42,
  },
  {
    name: 'Ether',
    address: '0x2170ed0880ac9a755fd29b2688956bd959f933f8',
    decimals: 18,
    symbol: 'ETH',
    chainId: 56,
  },
  {
    name: 'Wrapped AVAX',
    address: '0xd9d01a9f7c810ec035c0e42cb9e80ef44d7f8692',
    decimals: 18,
    symbol: 'WAVAX',
    chainId: 43113,
  },
  {
    name: 'Wrapped AVAX',
    address: '0xb31f66aa3c1e785363f0875a1b74e27b85fd66c7',
    decimals: 18,
    symbol: 'WAVAX',
    chainId: 43114,
  },
  {
    name: 'AirSwap Token',
    address: '0xcc1cbd4f67cceb7c001bd4adf98451237a193ff8',
    decimals: 4,
    symbol: 'AST',
    chainId: 4,
  },
  {
    name: 'AirSwap Token',
    address: '0x1a1ec25dc08e98e5e93f1104b5e5cdd298707d31',
    decimals: 4,
    symbol: 'AST',
    chainId: 5,
  },
  {
    name: 'AirSwap Token',
    address: '0x1a1ec25dc08e98e5e93f1104b5e5cdd298707d31',
    decimals: 4,
    symbol: 'AST',
    chainId: 42,
  },
  {
    name: 'AirSwap Token',
    address: '0x1ac0d76f11875317f8a7d791db94cdd82bd02bd1',
    decimals: 4,
    symbol: 'AST',
    chainId: 56,
  },
  {
    name: 'AirSwap Token',
    address: '0x48c427e7cEf42399e9e8300fC47875772309e995',
    decimals: 18,
    symbol: 'AST',
    chainId: 43113,
  },
  {
    name: 'AirSwap Token',
    address: '0xc32a3c867abad28d977e1724f92d9684ff3d2976',
    decimals: 18,
    symbol: 'AST',
    chainId: 43114,
  },
  {
    name: 'Dai',
    address: '0x5592ec0cfb4dbc12d3ab100b257153436a1f0fea',
    decimals: 18,
    symbol: 'DAI',
    chainId: 4,
  },
]

export const ERC20_BYTES32_ABI = [
  {
    constant: true,
    inputs: [],
    name: 'name',
    outputs: [{ name: '', type: 'bytes32' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
  },
  {
    constant: false,
    inputs: [
      { name: '_spender', type: 'address' },
      { name: '_value', type: 'uint256' },
    ],
    name: 'approve',
    outputs: [{ name: '', type: 'bool' }],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    constant: true,
    inputs: [],
    name: 'totalSupply',
    outputs: [{ name: '', type: 'uint256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
  },
  {
    constant: false,
    inputs: [
      { name: '_from', type: 'address' },
      { name: '_to', type: 'address' },
      { name: '_value', type: 'uint256' },
    ],
    name: 'transferFrom',
    outputs: [{ name: '', type: 'bool' }],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    constant: true,
    inputs: [],
    name: 'decimals',
    outputs: [{ name: '', type: 'uint8' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
  },
  {
    constant: true,
    inputs: [{ name: '_owner', type: 'address' }],
    name: 'balanceOf',
    outputs: [{ name: 'balance', type: 'uint256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
  },
  {
    constant: true,
    inputs: [],
    name: 'symbol',
    outputs: [{ name: '', type: 'bytes32' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
  },
  {
    constant: false,
    inputs: [
      { name: '_to', type: 'address' },
      { name: '_value', type: 'uint256' },
    ],
    name: 'transfer',
    outputs: [{ name: '', type: 'bool' }],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    constant: true,
    inputs: [
      { name: '_owner', type: 'address' },
      { name: '_spender', type: 'address' },
    ],
    name: 'allowance',
    outputs: [{ name: '', type: 'uint256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
  },
  { payable: true, stateMutability: 'payable', type: 'fallback' },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'owner', type: 'address' },
      { indexed: true, name: 'spender', type: 'address' },
      { indexed: false, name: 'value', type: 'uint256' },
    ],
    name: 'Approval',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'from', type: 'address' },
      { indexed: true, name: 'to', type: 'address' },
      { indexed: false, name: 'value', type: 'uint256' },
    ],
    name: 'Transfer',
    type: 'event',
  },
]

export const ERC20_ABI = [
  {
    constant: true,
    inputs: [],
    name: 'name',
    outputs: [{ name: '', type: 'string' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
  },
  {
    constant: false,
    inputs: [
      { name: '_spender', type: 'address' },
      { name: '_value', type: 'uint256' },
    ],
    name: 'approve',
    outputs: [{ name: '', type: 'bool' }],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    constant: true,
    inputs: [],
    name: 'totalSupply',
    outputs: [{ name: '', type: 'uint256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
  },
  {
    constant: false,
    inputs: [
      { name: '_from', type: 'address' },
      { name: '_to', type: 'address' },
      { name: '_value', type: 'uint256' },
    ],
    name: 'transferFrom',
    outputs: [{ name: '', type: 'bool' }],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    constant: true,
    inputs: [],
    name: 'decimals',
    outputs: [{ name: '', type: 'uint8' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
  },
  {
    constant: true,
    inputs: [{ name: '_owner', type: 'address' }],
    name: 'balanceOf',
    outputs: [{ name: 'balance', type: 'uint256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
  },
  {
    constant: true,
    inputs: [],
    name: 'symbol',
    outputs: [{ name: '', type: 'string' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
  },
  {
    constant: false,
    inputs: [
      { name: '_to', type: 'address' },
      { name: '_value', type: 'uint256' },
    ],
    name: 'transfer',
    outputs: [{ name: '', type: 'bool' }],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    constant: true,
    inputs: [
      { name: '_owner', type: 'address' },
      { name: '_spender', type: 'address' },
    ],
    name: 'allowance',
    outputs: [{ name: '', type: 'uint256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
  },
  { payable: true, stateMutability: 'payable', type: 'fallback' },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'owner', type: 'address' },
      { indexed: true, name: 'spender', type: 'address' },
      { indexed: false, name: 'value', type: 'uint256' },
    ],
    name: 'Approval',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'from', type: 'address' },
      { indexed: true, name: 'to', type: 'address' },
      { indexed: false, name: 'value', type: 'uint256' },
    ],
    name: 'Transfer',
    type: 'event',
  },
]
